toolb = nuke.menu('Nodes')
toolb.addCommand('AleeneGamma',"nuke.createNode('AleeneGamma')")
toolb.addCommand('AleeneContrast',"nuke.createNode('AleeneContrast')")
toolb.addCommand('AleeneSharpen',"nuke.createNode('AleeneSharpen')")
toolb.addCommand('AleeneMedian',"nuke.createNode('AleeneMedian')")
toolb.addCommand('AleeneOver',"nuke.createNode('AleeneOver')")
